source 'https://github.com/CocoaPods/Specs.git'

target 'TokenCell', :exclusive => true do
  pod "TokenCell", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TokenCell", :path => "../"

  #pod 'Specta', '~> 0.2.1'
  #pod 'Expecta'
  #pod 'FBSnapshotTestCase'
  #pod 'Expecta+Snapshots'
end
